bookmytable/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservation.urls'), name='reservation.urls'),
]

reservation/urls.py
from django.urls import path
from .views import TableListView, BookingListView, TableDetailView, BookingCancelView


app_name ='reservation'

urlpatterns = [
    
    path('', TableListView, name='TableListView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    
    path('table/<category>', TableDetailView.as_view(), name='TableDetailView'),
    path('booking_cancel/<pk>', BookingCancelView.as_view(),
         name='BookingCancelView'),
]

reservation/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

class Table(models.Model):
    
    TABLE_CATEGORIES = [
        ('A', 'Table for 3 people'),
        ('B', 'Table for 4 people'),
        ('C', 'Table for 6 people'),
        ('D', 'Table for 5 people'),
        ('E', 'Table for 2 people'),
        ('F', 'Table for 4 people'),
        ('G', 'Table for 6 people'),
        
    ]
    number = models.IntegerField(default=0)
    category = models.CharField(max_length=1, choices=TABLE_CATEGORIES)
    seats = models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.number}. Table for {self.seats} people'   
    

class Booking(models.Model):  
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    
    time = models.TimeField()
    date = models.DateField()
    
    def __str__(self):
        return f'{self.user} booked {self.table}  Date {self.date} Time {self.time}'


def get_table_category(self):
    table_categories = dict(self.table.TABLE_CATEGORIES)
    table_category = table_categories.get(self.table.category)
    return table_category


def get_cancel_booking_url(self):
    return reverse_lazy('reservation:BookingCancelView', args=[self.pk, ])

reservation/forms.py
from django import forms
from datetime import datetime
from django.core.exceptions import ValidationError
from .models import Booking


class AvailabilityForm(forms.Form):
    
   
    date = forms.DateField(
        required=True, input_formats=["%Y-%m-%dT", "%Y-%m-%dT"], widget=forms.DateInput(attrs={'type': 'datet-local'}))
    time = forms.TimeField(
        required=True, input_formats=["%H:%M", "%H:%M%Z"], widget=forms.TimeInput(attrs={'type': 'time-local'}))
    
    def check_working_hours(self, start, end):
        
        time = self.cleaned_data.get('time')
        date = self.cleaned_data.get('date')
        # This ensures that  booking handle between start and end of working hours.
        if not(time < start and time > end):
            raise ValidationError(
                "Times beyond working hours, please enter value within working hours")
        else:
            return self.cleaned_data

reservation/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import ListView, View, DeleteView
from .models import Table, Booking
from django.urls import (get_resolver, get_urlconf, resolve, reverse_lazy,
                         reverse, NoReverseMatch)
from django.core.exceptions import ImproperlyConfigured
from .forms import AvailabilityForm
from reservation.availabilities import check_availability


def TableListView(request):
    table = Table.objects.all()[0]
    table_categories = dict(table.TABLE_CATEGORIES)
    #print('categories', table_categories)
    table_values = table_categories.values()
    
    #print('categories', table_values)
    table_list =[]

    for table_category in table_categories:
        table = table_categories.get(table_category)
        table_url = reverse('reservation:TableDetailView', kwargs={
                           'category': table_category,

                           })
        #print(table_url)
        table_list.append((table, table_url))
        context = {
            "table_list": table_list,
        }
        #print(table_list)
    return render(request, 'table_list_view.html', context)





class TableDetailView(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        table_list = Table.objects.filter(category=category)
        form = AvailabilityForm()
        
        if len(table_list)>0 :
            table = table_list[0]
            table_category=dict(table.TABLE_CATEGORIES).get(table.category,None)
            
            context={
                'table_category':table_category,
                'form':form,
                 }
            
            return render(request, 'table_detail_view.html', context)
        else:
            
            return HttpResponse('category doesnot exist')
        
  
    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        
        table_list = Table.objects.filter(category=category)
        form = AvailabilityForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

        available_tables = []
        for table in table_list:
            data = form.cleaned_data
            if check_availability(table, data['time'], data['date']):
                available_tables.append(table)

        
            if len(available_tables)>0:
                table = available_tables[0]
                booking = Booking.objects.create(
                    user=self.request.user,
                    table=table,
                    time=data['time'],
                    date=data['date']
            )
                booking.save()
                return HttpResponse(booking)
            else:
                return HttpResponse("all categories of table are booked, attempt another one")


class BookingListView(ListView):
    model = Booking
    template_name = "booking_list_view.html"

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list


class BookingCancelView(DeleteView):
    
    model = Booking
    template_name ="booking_cancel_view.html"
    #success url mean here url to redirect  after  successfully deleting object
    success_url = reverse_lazy('reservation:BookingListView')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>CodeStar Blog</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
       <div class="container-fluid">
           <span class="brand">Book My Table</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                 
                      
                  
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    {% endif %}
                </ul>
                
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Code Instituters</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
</body>

</html>

templates/booking_cancel_view.html
{% extends "base.html" %}

{% block content %}





 <!-- Main Content -->
 <div class="content">

    <!-- table Image -->
    <div class="image">
        <img
            src="https://res.cloudinary.com/dqh6bfpwq/image/upload/v1688938872/gallery-3_zjmtlt.jpg">
    </div>

    <!-- Table Details -->
    <div class="table">

        
        
        <!-- Div 2: Table Information -->
        <!--<div class="table-info">
            <h1>{{table_category}}</h1>
            
        </div>-->

        <!-- Div 3: Table canceling Form -->
        <form id="cancelling-form" action="" method="POST">

            {% csrf_token %}
            <h2>Are you sure you want to cancel this Booking? Details-</h2>
            
            <h3>{{booking.date}}</h3>

            <!-- Input Div -->
            <h3>{{booking.time.}}</h3>
            <div class="input-div">
                <button type="submit">Cancel the Booking</button>
            </div>

        </form>

    </div> <!-- END Table Div -->

</div> <!-- END Main Content Div -->
{% endblock %}

templates/booking_form.html
{% extends "base.html" %}
{% block content %}

    
      <div class="nav">
        <h3 id="logo">Tamiru Restaurant</h3>
        <!-- <ul class="navlist">
          <a href="/marina_beach_amenties.html">Amenties</a>
        </ul> -->
      </div>
    
    <div class="d-flex flex-column align-items-center justify-content-center check_availability"
    >
    
      <div class="headings m-4">
        <h1>Tamiru Bar and </h1>
        <h1>Restaurant </h1>
      </div>

      
      <form id="booking-form" action="" method="POST">

        {% csrf_token %}

        <!-- Input Div -->
        <div class="input-div">
            <label for="id_date">Date : </label>
            <input type="date" id="id_date"  required  name="date">
        </div>

        <!-- Input Div -->
        <div class="input-div">
            <label for="id_time">Time : </label>
            <input type="time" id="id_time" required name="time">
        </div>

        <!-- Input Div -->
        <div class="input-div">
            <button type="submit">Book a Table</button>
        </div>

    </form>
        

        
      
    
   

  {% endblock %}

templates/booking_list_view.html
{% extends "base.html" %}
{% block content %}
<div id="content">
    <div class="header">
        <div class="headings">
            <h1>Your Bookings</h1>
            <h2>Welcome dear {{user}}</h2>
        </div>
        <div class="home">
            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'reservation:TableListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>
        </div>

    </div>

    <div class="bookings">
        {% for booking in booking_list %}
        <div class="booking">
            
            <img
                src=" https://res.cloudinary.com/dqh6bfpwq/image/upload/v1688938872/gallery-3_zjmtlt.jpg">
            
            <div class="category">
                <h2>{{booking.get_table_category}}</h2>
            </div>
            <div class="date">
                <h3>Date: {{booking.date}}</h3>
            </div>
            <div class="time">
                <h3>Time: {{booking.time}}</h3>
            </div>
            <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                        class="far fa-2x fa-times-circle"> Cancel
                        Booking</i></a>
            </div>

                {% empty %}
            <h2>You have no upcoming booking</h2>
        </div>
        {% endfor %}
    </div>
        
    

</div>
{% endblock  %}

templates/home.html
{% extends "base.html" %}

{% block content %}
<!--<a class="navbar-brand" href="{% url 'home' %}"></a>


{% endblock %}

templates/table_detail_view.html
{% extends "base.html" %}
{% block content %}

<div class="content">
 <!-- Table Image -->
 <div class="image">
    <img
src="https://res.cloudinary.com/dqh6bfpwq/image/upload/v1688938872/gallery-3_zjmtlt.jpg">
</div>


    <!-- table Details --> 
<div class="table">

    <!-- Div 1: Back to Home -->
    <div class="home">
        <a href="{% url 'reservation:TableListView' %}"><i class="fas fa-arrow-alt-circle-left">home</i></a>
    </div>

    <!-- Div 2: tableInformation -->
    <div class="table-info">
        <h1>{{table_category}}</h1>
        
    </div>
    <form id="booking-form" action="" method="POST">

        {% csrf_token %}

        <!-- Input Div -->
        <div class="input-div">
            <label for="id_date">Date : </label>
            <input type="date" id="id_date"  required  name="date">
        </div>

        <!-- Input Div -->
        <div class="input-div">
            <label for="id_time">Time : </label>
            <input type="time" id="id_time" required name="time">
        </div>

        <!-- Input Div -->
        <div class="input-div">
            <button type="submit">Book a Table</button>
        </div>

    </form>
 
    
    
</div> <!-- END table Div -->

</div><!-- END content Div -->

{% endblock %}

templates/table_list_view.html
{% extends "base.html" %}
{% block content %}

<h2>Tables</h2>
<!-- Main Content -->
<div class="content">
  <!-- table1 -->
  <div id="table">
  {% for table_category, table_url in table_list %}
  <div class="table">
    
    <a href="{{table_url}}">
    <img
      src="https://res.cloudinary.com/dqh6bfpwq/image/upload/v1688938776/gallery-1_mft04e.jpg"
    />
    <h2>{{table_category}}<h2>
    <p>
    
    </p>
    </a>
  </div>
  
  {% endfor %}
</div>
</div>
<!-- endtable1 -->


<!-- endtable1 -->


 

{% endblock  %}